spring:
  application:
    name: microservice-api-gateway
  cloude:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 20000
        response-timeout: 20s

server:
  port: 46557
  connection-timeout: 300000
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 140.134.26.71
  client:
    serviceUrl:
      defaultZone: http://140.134.26.71:50608/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
    gateway:
      enabled: true
    
        

