spring:
  application:
    name: microservice-api-gateway
server:
  port: 0
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://140.134.26.71:50608/eureka/
management:
  endpoints:
    web:
      exposure:
        include: routes

